- name: ansible vs shell
  hosts: local
  connection: local
  tasks:
  - name: command module test
    ansible.builtin.shell cat etc/passwrd | grep root
    reguster: out_command

  - name: print out put
    ansible.builtin.debug:
      msg: "{{ out_command }}"
