- name: ansible vs shell
  hosts: local
  connection: local
  tasks:
  - name: command module test
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: out_command

  - name: print out put
    ansible.builtin.debug:
      msg: "{{ out_command }}"

  - name: command module test
    ansible.builtin.shell: ls -ltr > text.file
    register: File_output

  - name: print out put of file
    ansible.builtin.debug:
      msg: "{{ File_output }}"
