- name: convert lettrs
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS"
  tasks:
  - name: convert letters to upper
    ansible.builtin.debug:
      msg: "{{ course | upper }}"

  - name: convert letters to lower
    ansible.builtin.debug:
    msg: "{{ course | lower }}"