- name: check ip address
  hosts: local
  connection: local
  vars:
    myIp: "192.23.89.123"
  tasks:
  - name: check my ip address
    ansible.builtin.debug:
      msg: "{{ myIp | ansible.utils.ipv4 }}"