- name: demo on errorhandling
  hosts: local
  connection: local
  tasks:
  - name: check user is exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_error: true
  - name: print user input
    ansible.builtin.debug:
      msg: "{{ user_output }}"
