- name: play level var
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print variable
    ansible.builtin.debug:
      msg: "the sourse: {{ course }}, trainer is: {{ trainer }}"